use traefik to load balance multiple coinstacks
shapeshift/unchained pull request #110
Opened 2021-10-21 23:55 UTC by phewitt

It has become apparent that we need to be able to run multiple coinstacks locally. At first this would have required exposing each service at different ports.

So I decided to use a reverse proxy to handle all traffic to all container. Now the only ports exposed are port `80` for the reverse proxy and port `8080` for the proxies dashboard. all routing to coinstacks can be done via localhost now. For example

`api.bitcoin.localhost/docs`
`rabbit-admin.ethereum.localhost`
`mongo.bitcoin.localhost`

This should simplify networking locally.

To use this now simply run `docker-compose up` in the root of the project. Then run `docker-compose up` in the coinstacks you want to run.

2021-10-22 14:40 UTC, kaladinlight approved these changes

2021-10-22 17:19 UTC, mvpratt approved these changes

2021-10-22 19:44 UTC, elmutt approved these changes

2021-10-24 00:48 UTC, elmutt requested changes
Need to remove `unchained-local` from the `depends_on:` sections of bitcoin and ethereum `docker-compose.yml` for this to work.

Otherwise it gives:

```ERROR: Service 'api' depends on service 'unchained-local' which is undefined.```

2021-10-25 16:13 UTC, elmutt approved these changes

2021-10-25 16:57 UTC, merged