feat: add weth subparser
shapeshift/unchained pull request #393
Opened 2022-04-21 04:48 UTC by Soptq

This PR adds WETH parser to parse `deposit()` and `withdraw(wad)`

close #389

2022-04-21 06:34 UTC, 0xApotheosis requested changes
Nice one @Soptq, glad to see you back in our codebase!

Could you please add tests for the new parser in `ethereum.test.ts`? You'll need to add 2 additional transactions, a deposit and withdraw, that go through this parser to the `mockData` directory.

2022-04-21 17:35 UTC, elmutt commented
Thanks @Soptq this looks great! It looks like some tests are failing CI but otherwise this looks like exactly what we need

I will be mostly away from my computer for the next couple of days. I'll be back on Monday and will be to to take a closer look, test it locally and get it merged.

2022-04-21 21:31 UTC, 0xApotheosis requested changes
Thanks for adding test @Soptq.

It appears that the WETH withdrawal is being parsed by the Yearn parser, instead of the new one you created - we'll need to address that.

2022-04-22 03:13 UTC, Soptq commented
> Thanks for adding test @Soptq.
> 
> It appears that the WETH withdrawal is being parsed by the Yearn parser, instead of the new one you created - we'll need to address that.

Fixed, it turns out to be a bug in the yearn parser, allowing the yearn parser to capture transactions even if they are not yearn-related.

2022-04-23 02:39 UTC, 0xApotheosis approved these changes
Some non-blocking comments, looking good!

2022-04-23 02:39 UTC, 0xApotheosis commented on node/packages/client/src/ethereum/parser/yearn.ts
> +    switch (txSigHash) {
Nice catch and refactor.

2022-04-23 02:39 UTC, 0xApotheosis commented on node/packages/client/src/ethereum/parser/yearn.ts
> +        // here receiveAddress should be the address of the shapeShiftRouter contract
We can probably remove this comment, as its content is described by the code.

2022-04-23 02:39 UTC, 0xApotheosis commented on node/packages/client/src/ethereum/parser/yearn.ts
> +        if (receiveAddress && receiveAddress !== SHAPE_SHIFT_ROUTER_CONTRACT) return
```suggestion
        if (receiveAddress !== SHAPE_SHIFT_ROUTER_CONTRACT) return
```

2022-04-25 16:37 UTC, elmutt commented
@Soptq @0xApotheosis 

I was just testing this PR locally and noticed some weth transactions unrelated to yearn are being processed by the yearn parser.

For example this TX:

https://etherscan.io/tx/0x29ed7ad51bbc568172d3d97bc79738a921e7dc669abbf15ab5198d97cc74614b

Gives:

```
{
  address: '0xE7F92E3d5FDe63C90A917e25854826873497ef3D',
  blockHash: '0x048e94784ee6376f08ce9e86e62ee304f3dfbb05b502f415ebc3ac090f939a1a',
  blockHeight: 14611926,
  blockTime: 1650322508,
  caip2: 'eip155:1',
  chain: 'ethereum',
  confirmations: 42907,
  fee: { caip19: 'eip155:1/slip44:60', value: '1087028000000000' },
  status: 'confirmed',
  tradeDetails: undefined,
  transfers: [
    {
      caip19: 'eip155:1/slip44:60',
      from: '0xE7F92E3d5FDe63C90A917e25854826873497ef3D',
      to: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      type: 'send',
      value: '3264000000000000'
    }
  ],
  txid: '0x29ed7ad51bbc568172d3d97bc79738a921e7dc669abbf15ab5198d97cc74614b',
  data: { method: 'deposit', parser: 'yearn' }
}
```

Parser should be `weth` in this case because the tx has nothing to do with yearn and should be going through the weth parser.

2022-04-25 16:40 UTC, elmutt requested changes
See comment

2022-04-25 16:54 UTC, Soptq commented
> https://etherscan.io/tx/0x29ed7ad51bbc568172d3d97bc79738a921e7dc669abbf15ab5198d97cc74614b

Hi @elmutt , I believe the transaction you tested is related to WETH. This transaction interacts with contract 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2, which is the contract address of WETH. In other words, this transaction is indeed calling the `deposit` function of the WETH contract instead of yearn.

I think yearn probably proxy some WETH deposit/withdraw related operations to the WETH contract.

2022-04-25 17:33 UTC, Soptq commented
Hi @elmutt , It seems I can't reproduce this problem. I added your provided transaction to the test:
- https://github.com/shapeshift/unchained/blob/87c1461465c45481224024b7680a14ec588b59b9/node/packages/client/src/ethereum/parser/__tests__/mockData/wethDeposit2.ts#L1-L35
-  https://github.com/shapeshift/unchained/blob/87c1461465c45481224024b7680a14ec588b59b9/node/packages/client/src/ethereum/parser/__tests__/ethereum.test.ts#L1318-L1372
and the test succeeded without problems as CI suggested.

@0xApotheosis Could you be able to reproduce this problem?

2022-04-25 19:16 UTC, elmutt commented
@Soptq im looking into it a bit more now will let you know what I find

2022-04-25 20:26 UTC, elmutt commented
> Hi @elmutt , It seems I can't reproduce this problem. I added your provided transaction to the test:
> 
> * https://github.com/shapeshift/unchained/blob/87c1461465c45481224024b7680a14ec588b59b9/node/packages/client/src/ethereum/parser/__tests__/mockData/wethDeposit2.ts#L1-L35
> * https://github.com/shapeshift/unchained/blob/87c1461465c45481224024b7680a14ec588b59b9/node/packages/client/src/ethereum/parser/__tests__/ethereum.test.ts#L1318-L1372
>   
>   and the test succeeded without problems as CI suggested.
> 
> @0xApotheosis Could you be able to reproduce this problem?

@Soptq I apologize, I was testing the wrong branch. On the correct branch the parser is correctly appearing as "weth"

I think I did find a small issue tho:

1) the "from" and "to" addresses on the weth transfers appear reversed. For example a weth "deposit" is creating new "weth" tokens for the user so the "to" address should be the users address and the "from" should be the contract address. (It looks reversed for withdraw as well, withdraw is a weth transfer from the user to the contract)

Otherwise this PR looks great and will get it merged & bounty paid after that last issue is fixed

2022-04-26 02:41 UTC, Soptq commented
@elmutt Done! Thanks for your suggestions ;)

2022-04-26 16:17 UTC, elmutt commented on node/packages/client/src/ethereum/parser/weth.ts
>                type: TransferType.Receive,
Should be `TransferType.Send`

2022-04-26 16:38 UTC, asamere approved these changes

2022-04-26 17:27 UTC, elmutt approved these changes

2022-04-26 17:29 UTC, merged

2022-04-26 17:30 UTC, elmutt commented
@Soptq Thanks for the the great work! Will get bounty paid out asap.